### ISSUE TITLE
IIS Express is already running

### ISSUE THREAD

**Issue by benxionghu** [warrenbuckley/IIS-Express-Code#411]
The first time I officially started the project with IIS, it was successful;
And when I do that
![image](https://user-images.githubusercontent.com/33918700/124241261-2cc56c80-db4e-11eb-83d2-2f12f62e91b3.png)

My application is going to be closed and that's normal;

But when I start IIS Restart again it will show IIS Express is already running  
I can only do that if I reopen VS code. Why is that

I think this is a process that didn't release IIS

Could you please give me a good idea?

**Comment by warrenbuckley** [comment]
Hello @1301536601 
Can you give me some specifics please on how I can reproduce this?

What version of Windows
What version of VSCode
What version of the IIS Express extension

**Comment by warrenbuckley** [comment]
I will close this issue for now as yet to have reproduction steps for me to help fix this.
If this is still a problem, please re-open this issue with some steps that I can try to help fix this

**Comment by mateiacd** [comment]
It is very easy to reproduce.
1. Create a folder, then create a simple HTML page in it.
2. Open the folder in VS Code, doesn't matter which version, assume the latest version 1.64.2
    I use the "IIS Express for VSCode" extension version 1.5
3. Press Ctrl+F5, the HTML page is displayed in the browser
4. Now instead of issuing the command "Stop WebSite" (Shift+F5) from the Command Palette, go to the tray icon and exit IIS Express manually from the "Exit" menu option. When asked to stop all worker processes, click Yes.
5. Press Ctrl+F5 again. You will see that this time the HTML page is not displayed correctly in the browser.
6. If you try instead Ctrl+Shift+F5, you will see the message box "IIS Express is already running"
