### ISSUE TITLE
Debugging

### ISSUE THREAD

**Issue by jesperordrup** [warrenbuckley/IIS-Express-Code#60]
Hi Warrem,

Is it possible to enable debugging of razor/app_code etc?

See u!
Jesper

**Comment by warrenbuckley** [comment]
Hi @jesperordrup 
This is something this tool will not do, as it simply allows the current folder/workspace to be run as a site in IISExpress.

The C# extension from Microsoft is more geared towards .NET Core work and that could fit your needs perhaps, otherwise debug with Visual Studio or Rider perhaps?

**Comment by jesperordrup** [comment]
Thx, Warren. I really enjoy using VS code over Visual studio. And your plugin is a great win. (its huuuuge)

best
Jesper

ps. Thanks for suggesting Visual studio :-)
